declare var jsScroll: (d: string, w: number, c: string) => void;
declare var groupArgField: any;
declare var webFxchat: string;
declare var getHistoryMsgs: (i: number, d: any) => void;
declare var joinQuitGroupFn: (t: string, i: any) => void;
declare var UserIdentity: any;
declare var layer: any;
declare var openChatFn: (v?: any) => void;
declare var getCookie: (v: string) => any;
declare var groupType: any;
declare var topicId: any;
declare var renderGroupBar: (g: any, b?: boolean) => any;
declare var concatMinibarList: (f: any) => void;
declare var nim: any;
declare var chatUI: any;
declare var webChat: any;
declare var data: any;
declare var getSession: (id: any) => any;
declare var ReadReceipt: (t: any) => void;
declare var addGroupList: object[];
declare var nimdata: any;
declare var MessageType: any;
declare var AnexcuseModel: (Tid: string, OffChatEndTime: number) => void;
declare var sendCustomSysMsg: (data: object) => void;
declare var getGroupManager: (groupid: string | number) => Array<string | number>;
declare var isImg: (str: string, cb?: any) => string;
declare var escapeFilter: (str: string) => string;
declare var ck: any;
declare var grounpArgConfig: (Tid: number | string) => void;
declare var unreadFn: (session: object) => void;
declare var MsgType: any;
declare var PopupMethod: any;
declare var chatHtml: any;
declare var fxchatMiniFn: () => void;
declare var strlen: (str: string) => any;